# Generated by Django 3.0.8 on 2021-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210524_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
